title: Move Planner Project
description: A system for helping people who are moving house, by letting them keep track of the contents of boxes
author: Benjamin Jenner

development: true
picotheme: red

